services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: network_default
    external: true

volumes:
  portainer_data:
    external: true
