services:
  smtp-relay:
    image: devture/exim-relay:latest
    container_name: smtp-relay
    restart: unless-stopped
    environment:
      LOCAL_ADDRESS: 0.0.0.0
      RELAY_FROM_HOSTS: 172.16.0.0/12
      SMARTHOST_ADDRESS: mail.smtp2go.com
      SMARTHOST_PORT: "2525"
      SMARTHOST_AUTH_USERNAME: ${SMTP2GO_USER}
      SMARTHOST_AUTH_PASSWORD: ${SMTP2GO_PASSWORD}

networks:
  default:
    name: network_default
    external: true
