services:
  termix:
    image: bugattiguy527/termix:latest
    container_name: termix
    restart: unless-stopped
    network_mode: host
    volumes:
     - /docker/termix-data:/app/data
    environment:
      PORT: "8081"

volumes:
  termix-data:
    driver: local
networks:
  dev_default:
    external: true