version: "3.8" # Docker Compose file format version

services:
  # Main application service
  tandoor:
    container_name: tandoor
    image: vabene1111/recipes
    restart: unless-stopped
    volumes:
      - /data/recipes/staticfiles:/opt/recipes/staticfiles
      - /data/recipes/mediafiles:/opt/recipes/mediafiles
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=${RECIPES_SECRET_KEY}
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=tandoor-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=djangodb
    depends_on:
      - tandoor-db

  # PostgreSQL database service
  tandoor-db:
    image: postgres:16-alpine
    container_name: tandoor-db
    volumes:
      - /docker/db_recipes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=djangodb
    restart: always

# Volume definitions for the application
volumes:
  staticfiles:
    driver: local
  mediafiles:
    driver: local
  postgresql_data:
    driver: local

networks:
  default:
    name: network_default
    external: true